# syntax=docker/dockerfile:1

ARG NODE_VERSION=24

FROM node:${NODE_VERSION}-bookworm-slim AS frontend-build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.29-alpine AS frontend
COPY --from=frontend-build /app/dist /usr/share/nginx/html
RUN rm /docker-entrypoint.d/20-envsubst-on-templates.sh
COPY docker/20-envsubst-on-templates.sh /docker-entrypoint.d/20-envsubst-on-templates.sh
COPY docker/nginx.conf.template /etc/nginx/templates/default.conf.template
RUN chmod +x /docker-entrypoint.d/20-envsubst-on-templates.sh
EXPOSE 80
